In [17]:
c_list=[(1,2,3,4),(5,6,7,8)]
print(c_list)

[(1, 2, 3, 4), (5, 6, 7, 8)]


In [18]:
c_list

[(1, 2, 3, 4), (5, 6, 7, 8)]

In [19]:
import numpy as np
arr=np.array(c_list)
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [20]:
arr


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(2,22,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [25]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [30]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.ones(2)

array([1., 1.])

In [36]:
np.eye(3)
#returns an identity matrix of given order

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.random.rand(5) 
# random numbers uniformly distributed from 0 to 1

array([0.76317966, 0.65035906, 0.10952758, 0.06772786, 0.36257008])

In [33]:
np.random.rand(4,6)

array([[0.85531327, 0.25653432, 0.10854077, 0.01012974, 0.89738245,
        0.43228602],
       [0.28253906, 0.5914637 , 0.32944578, 0.70500303, 0.76554668,
        0.0503267 ],
       [0.58147547, 0.93915788, 0.46274734, 0.2769586 , 0.00452931,
        0.07747331],
       [0.90210498, 0.09730154, 0.1398091 , 0.87403647, 0.24349823,
        0.47348249]])

In [35]:
np.random.randint(2,75)
#2 has a chance of being selected but 75 does'nt

25

In [40]:
np.random.randint(3,100,6)

array([37, 46, 92,  5, 15,  4])

In [38]:
np.random.randn(4)
#random numbers from central normal distibution centred around zero 

array([-1.45688915, -0.08741232,  1.37025622, -0.70374733])

In [39]:
np.random.randn(2,3)

array([[ 0.99235493,  0.95057001,  0.1534064 ],
       [-0.14067145, -0.00775154, -0.37330065]])